version: '3.8'

services:
  # Основной бот AI Chatter с встроенным Custom MCP сервером
  ai-chatter-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chatter-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NOTION_PARENT_PAGE_ID=${NOTION_PARENT_PAGE_ID}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # Custom MCP настройки
      - NOTION_MCP_SERVER_PATH=/app/notion-mcp-server
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
